### PR TITLE
What I learn about Internet Fundamentals.md

### PR DESCRIPTION
**Pull request by rahulkamilya**
> **ISP**
> **DNS**
> **HTTP VS HTTPS**
> **HTTP Status Codes**
> **Check IP By CMD**
> **Ports**

### CODE REVIEW

**Comment by rahulkamilya** [comment]
(:

**Review by chandannkrp — APPROVED** [review]
All good @Abbhiishek  ✅

**Comment by Abbhiishek** [comment]
LFTM 🎉

**Review by Abbhiishek — APPROVED** [review]
Nice Write up Structure :)

**Pull request merged**
